# -*- coding: utf-8 -*-
"""Untitled3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Gmnlakw3Qr1fe2jF26dYMeXk3IJOGgPH
"""

pip install opencv-python

from google.colab.patches import cv2_imshow
import cv2
rasm1=cv2.imread("husniddin.jpg")
rasm2=cv2.imread("husniddin2.jpg")
rasm3=cv2.imread("husniddin3.jpg")
rasm4=cv2.imread("husniddin4.jpg")
rasm5=cv2.imread("husniddin5.jpg")
cv2_imshow(rasm1)
cv2_imshow(rasm2)
cv2_imshow(rasm3)
cv2_imshow(rasm4)
cv2_imshow(rasm5)

oqqora=cv2.cvtColor(rasm1,cv2.COLOR_BGR2GRAY)
cv2_imshow(oqqora)
oqqora=cv2.cvtColor(rasm2,cv2.COLOR_BGR2GRAY)
cv2_imshow(oqqora)
oqqora=cv2.cvtColor(rasm3,cv2.COLOR_BGR2GRAY)
cv2_imshow(oqqora)
oqqora=cv2.cvtColor(rasm4,cv2.COLOR_BGR2GRAY)
cv2_imshow(oqqora)
oqqora=cv2.cvtColor(rasm5,cv2.COLOR_BGR2GRAY)
cv2_imshow(oqqora)